import "../styles/globals.css";
import Header from "./Header";

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </head>
            <body>
                <div className="min-h-scren w-full bg-secondary-neutral font-elkjop-regular relative">
                    <div className="min-h-screen max-w-screen-2xl mx-auto bg-white w-full">
                        <Header />
                        {/* <QuickMenu quickMenuLinks={quickMenuLinks} /> */}

                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
